// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';
import 'package:yaml_edit/yaml_edit.dart';

/// The outcome of computing an edit for an overrides file —
/// `pubspec_overrides.yaml` (Dart) or `pnpm-workspace.yaml` (TypeScript).
///
/// The three states are mutually exclusive: the file stays as it is, it gets
/// [content] written to it, or it is deleted. Edits are computed without
/// touching the disk so a command can collect them in a
/// `FileChangesBuffer` and apply them all at once.
class PubspecOverridesEdit {
  /// Nothing needs to change.
  const PubspecOverridesEdit.unchanged() : content = null, deleteFile = false;

  /// [content] must be written to the file.
  const PubspecOverridesEdit.write(this.content) : deleteFile = false;

  /// The file must be deleted.
  const PubspecOverridesEdit.delete() : content = null, deleteFile = true;

  /// The new file content, or null when the file is unchanged or deleted.
  final String? content;

  /// Whether the file must be deleted.
  final bool deleteFile;

  /// Whether the file stays as it is.
  bool get isUnchanged => content == null && !deleteFile;
}

/// Reads and edits the `dependency_overrides` of a `pubspec_overrides.yaml`.
///
/// `pubspec_overrides.yaml` is a local-only sibling of `pubspec.yaml` that pub
/// reads in addition to it. Redirecting a reference through this file instead
/// of rewriting `pubspec.yaml` keeps the published dependency constraints
/// intact, so the package stays publishable and its manifest stays free of
/// developer-machine specific paths and feature branch pins.
///
/// Two kinds of overrides are written: a `path` pointing at the sibling
/// checkout (local mode) and a `git` ref pinning the ticket's feature branch
/// (git feature branch mode). They are mutually exclusive - writing one
/// replaces the other.
///
/// All edits merge into an existing file: entries this package does not own are
/// preserved, and the file is only deleted when nothing but our own overrides
/// was left in it.
class PubspecOverridesIo {
  /// Creates the io helper.
  const PubspecOverridesIo();

  /// The name of the overrides file.
  static const String fileName = 'pubspec_overrides.yaml';

  /// The header written above a freshly created overrides file with local
  /// path overrides.
  static const String headerComment =
      '# Generated by gg_localize_refs. Overrides the dependencies of\n'
      '# pubspec.yaml with the local sibling checkouts of this workspace.\n'
      '# The paths are relative, so this file travels with the ticket branch.\n'
      '# change-refs-to-git-feature-branch and change-refs-to-pub-dev\n'
      '# remove it again.\n';

  /// The header written above a freshly created overrides file with git
  /// feature branch overrides.
  static const String gitHeaderComment =
      '# Generated by gg_localize_refs. Overrides the dependencies of\n'
      '# pubspec.yaml with the feature branch of this ticket, so the\n'
      '# repositories of the ticket are reviewed against each other.\n'
      '# change-refs-to-local and change-refs-to-pub-dev remove it again.\n';

  /// Returns the overrides file of the project in [projectDir].
  File file(Directory projectDir) => File(p.join(projectDir.path, fileName));

  /// Computes the edit that declares a `path` override for every entry of
  /// [pathsByDependency] (dependency name → path relative to [projectDir]).
  ///
  /// See [_addOverrides] for how the edit is merged into an existing file.
  PubspecOverridesEdit addPathOverrides({
    required Directory projectDir,
    required Map<String, String> pathsByDependency,
    Map<String, dynamic> inheritedOverrides = const <String, dynamic>{},
  }) {
    return _addOverrides(
      projectDir: projectDir,
      overridesByDependency: <String, dynamic>{
        for (final entry in pathsByDependency.entries)
          entry.key: <String, dynamic>{'path': entry.value},
      },
      inheritedOverrides: inheritedOverrides,
      header: headerComment,
    );
  }

  /// Computes the edit that declares a `git` override for every entry of
  /// [gitUrlsByDependency] (dependency name → git url), all pinned to [ref].
  ///
  /// The result is the shape [isOwnedGitOverride] recognizes again, so
  /// `change-refs-to-pub-dev` can drop exactly these entries later. See
  /// [_addOverrides] for how the edit is merged into an existing file.
  PubspecOverridesEdit addGitOverrides({
    required Directory projectDir,
    required Map<String, String> gitUrlsByDependency,
    required String ref,
    Map<String, dynamic> inheritedOverrides = const <String, dynamic>{},
  }) {
    return _addOverrides(
      projectDir: projectDir,
      overridesByDependency: <String, dynamic>{
        for (final entry in gitUrlsByDependency.entries)
          entry.key: <String, dynamic>{
            'git': <String, dynamic>{'url': entry.value, 'ref': ref},
          },
      },
      inheritedOverrides: inheritedOverrides,
      header: gitHeaderComment,
    );
  }

  /// Computes the edit that declares [overridesByDependency] (dependency name
  /// → override value) in the overrides file of [projectDir].
  ///
  /// [inheritedOverrides] are the `dependency_overrides` declared in
  /// `pubspec.yaml`. Pub does not merge the two sections: as soon as
  /// `pubspec_overrides.yaml` exists it replaces the one of `pubspec.yaml`
  /// entirely. They are therefore carried over, unless the overrides file
  /// already declares the same name.
  ///
  /// [header] is put on top of a file that has to be created from scratch.
  ///
  /// Returns an unchanged edit when every dependency is already overridden
  /// with exactly that value, so running a command twice is a no-op.
  PubspecOverridesEdit _addOverrides({
    required Directory projectDir,
    required Map<String, dynamic> overridesByDependency,
    required Map<String, dynamic> inheritedOverrides,
    required String header,
  }) {
    if (overridesByDependency.isEmpty) {
      return const PubspecOverridesEdit.unchanged();
    }

    final overridesFile = file(projectDir);
    final existing = overridesFile.existsSync()
        ? overridesFile.readAsStringSync()
        : null;
    final parsed = existing == null
        ? null
        : _parseOrThrow(existing, overridesFile);
    final section = parsed is Map ? parsed['dependency_overrides'] : null;

    final inherited = <String, dynamic>{
      for (final entry in inheritedOverrides.entries)
        if (!overridesByDependency.containsKey(entry.key) &&
            !(section is Map && section.containsKey(entry.key)))
          entry.key: entry.value,
    };

    // A dependency that was dropped from pubspec.yaml must lose its override:
    // pub pulls every overridden package into the resolution, whether the
    // manifest declares it or not.
    final stale = <String>[
      if (section is Map)
        for (final entry in section.entries)
          if (!overridesByDependency.containsKey(entry.key.toString()) &&
              !inheritedOverrides.containsKey(entry.key.toString()) &&
              (isOwnedPathOverride(
                    projectDir: projectDir,
                    name: entry.key.toString(),
                    value: entry.value,
                  ) ||
                  _isDeadPathOverride(
                    projectDir: projectDir,
                    value: entry.value,
                  )))
            entry.key.toString(),
    ];

    if (inherited.isEmpty &&
        stale.isEmpty &&
        section is Map &&
        overridesByDependency.entries.every(
          (entry) => _isSameOverride(section[entry.key], entry.value),
        )) {
      return const PubspecOverridesEdit.unchanged();
    }

    final newSectionEntries = <String, dynamic>{
      ...overridesByDependency,
      ...inherited,
    };

    // A missing, empty or comment-only file has no map to merge into. Build the
    // document from scratch and put the header back on top, because replacing
    // the root node drops the comments of the original text.
    if (parsed is! Map) {
      final editor = YamlEditor('');
      editor.update(<Object>[], <String, dynamic>{
        'dependency_overrides': newSectionEntries,
      });
      return PubspecOverridesEdit.write(_withTrailingNewline('$header$editor'));
    }

    final editor = YamlEditor(existing!);
    if (section is! Map) {
      // The key is absent or has a null value: yaml_edit cannot address
      // children of a scalar, so the whole section is written at once.
      editor.update(<Object>['dependency_overrides'], newSectionEntries);
    } else {
      for (final entry in newSectionEntries.entries) {
        editor.update(<Object>['dependency_overrides', entry.key], entry.value);
      }
      for (final name in stale) {
        editor.remove(<Object>['dependency_overrides', name]);
      }
    }

    final updated = _withTrailingNewline(editor.toString());
    return updated == existing
        ? const PubspecOverridesEdit.unchanged()
        : PubspecOverridesEdit.write(updated);
  }

  /// Computes the edit that removes the overrides this package owns from the
  /// overrides file of [projectDir].
  ///
  /// Removed are the `path` overrides of [dependencyNames] plus every other
  /// entry that points at a sibling checkout of the same name (see
  /// [isOwnedPathOverride]) - a dependency that was dropped from the manifest
  /// must not stay overridden - and the `git` overrides of [dependencyNames]
  /// that carry the shape `change-refs-to-git-feature-branch` writes (see
  /// [isOwnedGitOverride]). A hand written override such as a version
  /// constraint, or a git ref for a package that is no workspace dependency,
  /// is left alone. The file is deleted when nothing but an empty
  /// `dependency_overrides` section remains.
  PubspecOverridesEdit removeOwnedOverrides({
    required Directory projectDir,
    required Iterable<String> dependencyNames,
  }) {
    final overridesFile = file(projectDir);
    if (!overridesFile.existsSync()) {
      return const PubspecOverridesEdit.unchanged();
    }

    final existing = overridesFile.readAsStringSync();
    final parsed = _parseOrThrow(existing, overridesFile);
    final section = parsed is Map ? parsed['dependency_overrides'] : null;

    if (section is! Map) {
      return _isEffectivelyEmpty(parsed)
          ? const PubspecOverridesEdit.delete()
          : const PubspecOverridesEdit.unchanged();
    }

    final names = dependencyNames.toSet();
    final toRemove = <String>[
      for (final entry in section.entries)
        if ((_isPathOverride(entry.value) &&
                (names.contains(entry.key.toString()) ||
                    isOwnedPathOverride(
                      projectDir: projectDir,
                      name: entry.key.toString(),
                      value: entry.value,
                    ) ||
                    _isDeadPathOverride(
                      projectDir: projectDir,
                      value: entry.value,
                    ))) ||
            (names.contains(entry.key.toString()) &&
                isOwnedGitOverride(entry.value)))
          entry.key.toString(),
    ];

    if (toRemove.isEmpty) {
      return _isEffectivelyEmpty(parsed)
          ? const PubspecOverridesEdit.delete()
          : const PubspecOverridesEdit.unchanged();
    }

    final editor = YamlEditor(existing);
    for (final name in toRemove) {
      editor.remove(<Object>['dependency_overrides', name]);
    }

    final updated = editor.toString();
    if (_isEffectivelyEmpty(_parseOrThrow(updated, overridesFile))) {
      return const PubspecOverridesEdit.delete();
    }

    return PubspecOverridesEdit.write(_withTrailingNewline(updated));
  }

  // ...........................................................................
  /// Returns whether the override [name] → [value] looks like one this package
  /// writes: a bare `path` pointing at a sibling checkout of [projectDir] whose
  /// package name is [name].
  ///
  /// The overrides file may not carry a marker key - pub accepts only
  /// `dependency_overrides`, `resolution` and `workspace` - so ownership is
  /// derived from the shape of the entry.
  bool isOwnedPathOverride({
    required Directory projectDir,
    required String name,
    required dynamic value,
  }) {
    if (value is! Map || value.length != 1) {
      return false;
    }

    final path = value['path'];
    if (path is! String) {
      return false;
    }

    final projectPath = p.normalize(projectDir.absolute.path);
    final targetPath = p.normalize(p.join(projectPath, path));
    if (p.dirname(targetPath) != p.dirname(projectPath)) {
      return false;
    }

    final pubspec = File(p.join(targetPath, 'pubspec.yaml'));
    if (!pubspec.existsSync()) {
      return false;
    }

    try {
      final parsed = loadYaml(pubspec.readAsStringSync());
      return parsed is Map && parsed['name'] == name;
    } catch (_) {
      return false;
    }
  }

  /// Returns whether [value] is a bare `path` override pointing at a **missing
  /// sibling** of [projectDir].
  ///
  /// That is the exact shape this package writes, so the entry is ours even
  /// though ownership cannot be proven anymore - the package name it would have
  /// to match is unreadable once the checkout is gone. Keeping it is not an
  /// option: pub fails hard with "could not find package … at …", and as long
  /// as the entry stays, the overrides file cannot be deleted either, so the
  /// workspace can never leave local mode. A path reaching further out (a
  /// vendored `../../vendor/x`) is left alone - that one is hand written.
  bool _isDeadPathOverride({
    required Directory projectDir,
    required dynamic value,
  }) {
    if (value is! Map || value.length != 1) {
      return false;
    }

    final path = value['path'];
    if (path is! String) {
      return false;
    }

    final projectPath = p.normalize(projectDir.absolute.path);
    final targetPath = p.normalize(p.join(projectPath, path));
    if (p.dirname(targetPath) != p.dirname(projectPath)) {
      return false;
    }

    return !Directory(targetPath).existsSync();
  }

  /// Returns whether [value] is a git override of the shape
  /// `change-refs-to-git-feature-branch` writes: a single `git` key holding
  /// nothing but a `url` and a `ref`.
  ///
  /// Ownership is derived from the shape alone - the overrides file may not
  /// carry a marker key - so the callers additionally require the entry to
  /// name a workspace dependency. A git ref written by hand for anything else
  /// therefore survives.
  bool isOwnedGitOverride(dynamic value) {
    if (value is! Map || value.length != 1) {
      return false;
    }

    final git = value['git'];
    if (git is! Map || git.length != 2) {
      return false;
    }

    return git['url'] is String && git['ref'] is String;
  }

  /// Returns whether the existing override [value] already is [newValue].
  ///
  /// Compared structurally, one level deep - that covers both shapes this
  /// package writes (`{path: …}` and `{git: {url: …, ref: …}}`) and treats the
  /// `YamlMap` read from disk and the plain `Map` built here as equal.
  bool _isSameOverride(dynamic value, dynamic newValue) {
    if (value is! Map || newValue is! Map) {
      return value == newValue;
    }

    if (value.length != newValue.length) {
      return false;
    }

    for (final entry in newValue.entries) {
      if (!value.containsKey(entry.key)) {
        return false;
      }
      if (!_isSameOverride(value[entry.key], entry.value)) {
        return false;
      }
    }

    return true;
  }

  /// Returns whether [value] is an override declaring a local `path`.
  bool _isPathOverride(dynamic value) {
    return value is Map && value.containsKey('path');
  }

  /// Returns whether [parsed] carries nothing worth keeping the file for.
  bool _isEffectivelyEmpty(dynamic parsed) {
    if (parsed == null) {
      return true;
    }
    if (parsed is! Map) {
      return false;
    }
    if (parsed.isEmpty) {
      return true;
    }
    if (parsed.length > 1 || !parsed.containsKey('dependency_overrides')) {
      return false;
    }

    final section = parsed['dependency_overrides'];
    return section == null || (section is Map && section.isEmpty);
  }

  /// Parses [content] and throws a readable exception when it is not a YAML
  /// map. An empty or comment-only file parses to null and is accepted.
  ///
  /// A file whose root is a list or a scalar is rejected instead of being
  /// overwritten: pub would not accept it either, and silently dropping
  /// whatever the author put there is worse than saying so.
  dynamic _parseOrThrow(String content, File overridesFile) {
    final dynamic parsed;
    try {
      parsed = loadYaml(content);
    } catch (e) {
      throw Exception('Cannot parse ${overridesFile.path}: $e');
    }

    if (parsed != null && parsed is! Map) {
      throw Exception(
        'Cannot parse ${overridesFile.path}: expected a YAML map, '
        'got ${parsed.runtimeType}.',
      );
    }

    return parsed;
  }

  /// Returns [content] with exactly one trailing newline.
  String _withTrailingNewline(String content) {
    return content.endsWith('\n') ? content : '$content\n';
  }
}
