// @license
// Copyright (c) 2025 Göran Hegenberg. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:io';

import 'package:gg_localize_refs/src/backend/pubspec_overrides_io.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:yaml/yaml.dart';

import '../test_helpers.dart';

void main() {
  const io = PubspecOverridesIo();

  Directory projectDir = Directory('');
  late File overridesFile;

  setUp(() {
    projectDir = createTempDir('pubspec_overrides_io', 'project1');
    overridesFile = File(p.join(projectDir.path, PubspecOverridesIo.fileName));
  });

  tearDown(() {
    deleteDirs(<Directory>[projectDir.parent]);
  });

  /// The `dependency_overrides` of [content].
  Map<dynamic, dynamic> overridesOf(String content) {
    final parsed = loadYaml(content) as Map;
    return parsed['dependency_overrides'] as Map;
  }

  /// Creates a sibling checkout of [projectDir] holding a package [name].
  Directory createSibling(String name, {String? packageName}) {
    final dir = Directory(p.join(projectDir.parent.path, name))
      ..createSync(recursive: true);
    File(p.join(dir.path, 'pubspec.yaml')).writeAsStringSync(
      'name: ${packageName ?? name}\n'
      'version: 1.0.0\n',
    );
    return dir;
  }

  /// Creates a sibling directory `other` whose package name does NOT match the
  /// override key `other`, so an override for it is provably not ours.
  ///
  /// The directory has to exist: a missing sibling counts as an entry we wrote
  /// and lost track of, and would be pruned.
  void createForeignSibling() => createSibling(
    'other',
    packageName: 'a_package_nobody_overrides_by_that_name',
  );

  group('PubspecOverridesEdit', () {
    test('unchanged carries neither content nor a deletion', () {
      const edit = PubspecOverridesEdit.unchanged();
      expect(edit.isUnchanged, isTrue);
      expect(edit.content, isNull);
      expect(edit.deleteFile, isFalse);
    });

    test('write carries the content', () {
      const edit = PubspecOverridesEdit.write('a: 1\n');
      expect(edit.isUnchanged, isFalse);
      expect(edit.content, 'a: 1\n');
      expect(edit.deleteFile, isFalse);
    });

    test('delete asks for the deletion', () {
      const edit = PubspecOverridesEdit.delete();
      expect(edit.isUnchanged, isFalse);
      expect(edit.content, isNull);
      expect(edit.deleteFile, isTrue);
    });
  });

  group('PubspecOverridesIo', () {
    group('file()', () {
      test('returns pubspec_overrides.yaml of the project', () {
        expect(
          io.file(projectDir).path,
          p.join(projectDir.path, 'pubspec_overrides.yaml'),
        );
      });
    });

    group('addPathOverrides()', () {
      test('is unchanged for an empty request', () {
        expect(
          io
              .addPathOverrides(
                projectDir: projectDir,
                pathsByDependency: <String, String>{},
              )
              .isUnchanged,
          isTrue,
        );
      });

      test('creates the file with a header', () {
        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
        );

        expect(edit.deleteFile, isFalse);
        expect(edit.content, startsWith('# Generated by gg_localize_refs'));
        expect(edit.content, endsWith('\n'));
        expect((overridesOf(edit.content!)['a'] as Map)['path'], '../a');
      });

      test('writes one entry per dependency', () {
        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a', 'b': '../../b'},
        );

        final overrides = overridesOf(edit.content!);
        expect(overrides.keys, <String>['a', 'b']);
        expect((overrides['b'] as Map)['path'], '../../b');
      });

      test('quotes a path that needs quoting', () {
        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../my dir: weird'},
        );

        expect(
          (overridesOf(edit.content!)['a'] as Map)['path'],
          '../my dir: weird',
        );
      });

      test('merges into a hand written file and keeps its comments', () {
        createForeignSibling();
        overridesFile.writeAsStringSync(
          '# keep me\n'
          'dependency_overrides:\n'
          '  other:\n'
          '    path: ../other\n',
        );

        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
        );

        expect(edit.content, contains('# keep me'));
        final overrides = overridesOf(edit.content!);
        expect((overrides['other'] as Map)['path'], '../other');
        expect((overrides['a'] as Map)['path'], '../a');
      });

      test('fills a section that is present but null', () {
        overridesFile.writeAsStringSync(
          '# hdr\n'
          'dependency_overrides:\n',
        );

        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
        );

        expect(edit.content, contains('# hdr'));
        expect((overridesOf(edit.content!)['a'] as Map)['path'], '../a');
      });

      test('adds the section to a file that has other top level keys', () {
        // `resolution` is - next to `workspace` - the only other key pub
        // accepts in pubspec_overrides.yaml.
        overridesFile.writeAsStringSync('resolution: local\n');

        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
        );

        expect(edit.content, contains('resolution: local'));
        expect((overridesOf(edit.content!)['a'] as Map)['path'], '../a');
      });

      test('carries the dependency_overrides of pubspec.yaml over', () {
        // Pub replaces the section of pubspec.yaml instead of merging it, so
        // dropping the inherited entries would break the resolution. The values
        // come straight out of a parsed pubspec.yaml, i.e. they are yaml nodes.
        final inherited =
            loadYaml(
                  'dependency_overrides:\n'
                  '  pinned: 1.2.3\n'
                  '  vendored:\n'
                  '    path: ../../vendor/vendored\n',
                )['dependency_overrides']
                as Map<dynamic, dynamic>;

        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
          inheritedOverrides: <String, dynamic>{
            for (final entry in inherited.entries)
              entry.key.toString(): entry.value,
          },
        );

        final overrides = overridesOf(edit.content!);
        expect((overrides['a'] as Map)['path'], '../a');
        expect(overrides['pinned'], '1.2.3');
        expect((overrides['vendored'] as Map)['path'], '../../vendor/vendored');
      });

      test('does not overwrite an inherited entry that is already there', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  pinned: 9.9.9\n',
        );

        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
          inheritedOverrides: <String, dynamic>{'pinned': '1.2.3'},
        );

        expect(overridesOf(edit.content!)['pinned'], '9.9.9');
      });

      test('a localized dependency wins over its inherited override', () {
        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
          inheritedOverrides: <String, dynamic>{'a': '1.2.3'},
        );

        expect((overridesOf(edit.content!)['a'] as Map)['path'], '../a');
      });

      test('is unchanged when the inherited entries are carried over', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    path: ../a\n'
          '  pinned: 1.2.3\n',
        );

        expect(
          io
              .addPathOverrides(
                projectDir: projectDir,
                pathsByDependency: <String, String>{'a': '../a'},
                inheritedOverrides: <String, dynamic>{'pinned': '1.2.3'},
              )
              .isUnchanged,
          isTrue,
        );
      });

      test('replaces the header of a comment only file', () {
        overridesFile.writeAsStringSync('# just a comment\n');

        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
        );

        expect(edit.content, startsWith('# Generated by gg_localize_refs'));
        expect((overridesOf(edit.content!)['a'] as Map)['path'], '../a');
      });

      test('is unchanged when every path is already declared', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    path: ../a\n',
        );

        expect(
          io
              .addPathOverrides(
                projectDir: projectDir,
                pathsByDependency: <String, String>{'a': '../a'},
              )
              .isUnchanged,
          isTrue,
        );
      });

      test('updates a stale path', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    path: ../old_a\n',
        );

        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
        );

        expect((overridesOf(edit.content!)['a'] as Map)['path'], '../a');
      });

      test('replaces an override that is not a path', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a: ^1.0.0\n',
        );

        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
        );

        expect((overridesOf(edit.content!)['a'] as Map)['path'], '../a');
      });

      test('replaces a path override that carries extra keys', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    path: ../a\n'
          '    version: ^1.0.0\n',
        );

        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
        );

        expect(edit.isUnchanged, isFalse);
        expect((overridesOf(edit.content!)['a'] as Map).length, 1);
      });

      test(
        'prunes an override of a package that is no longer a dependency',
        () {
          createSibling('a');
          createSibling('gone');
          overridesFile.writeAsStringSync(
            'dependency_overrides:\n'
            '  a:\n'
            '    path: ../a\n'
            '  gone:\n'
            '    path: ../gone\n',
          );

          final edit = io.addPathOverrides(
            projectDir: projectDir,
            pathsByDependency: <String, String>{'a': '../a'},
          );

          final overrides = overridesOf(edit.content!);
          expect((overrides['a'] as Map)['path'], '../a');
          expect(overrides.containsKey('gone'), isFalse);
        },
      );

      test('keeps an override that points outside the workspace', () {
        createSibling('a');

        // The target has to EXIST and carry a matching package name, otherwise
        // the check short circuits before the workspace boundary matters and
        // the test would pass with the boundary guard removed.
        final vendored = Directory(
          p.join(projectDir.parent.parent.path, 'vendor', 'vendored'),
        )..createSync(recursive: true);
        File(p.join(vendored.path, 'pubspec.yaml')).writeAsStringSync(
          'name: vendored\n'
          'version: 1.0.0\n',
        );

        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    path: ../a\n'
          '  vendored:\n'
          '    path: ../../vendor/vendored\n',
        );

        expect(
          io
              .addPathOverrides(
                projectDir: projectDir,
                pathsByDependency: <String, String>{'a': '../a'},
              )
              .isUnchanged,
          isTrue,
        );

        vendored.parent.deleteSync(recursive: true);
      });

      test('prunes an override whose target directory vanished', () {
        createSibling('a');
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    path: ../a\n'
          '  gone:\n'
          '    path: ../gone\n',
        );

        final edit = io.addPathOverrides(
          projectDir: projectDir,
          pathsByDependency: <String, String>{'a': '../a'},
        );

        final overrides = overridesOf(edit.content!);
        expect((overrides['a'] as Map)['path'], '../a');
        expect(overrides.containsKey('gone'), isFalse);
      });

      test('keeps a sibling override whose package name differs', () {
        createSibling('a');
        final other = createSibling('other_dir');
        File(p.join(other.path, 'pubspec.yaml')).writeAsStringSync(
          'name: something_else\n'
          'version: 1.0.0\n',
        );
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    path: ../a\n'
          '  other_dir:\n'
          '    path: ../other_dir\n',
        );

        expect(
          io
              .addPathOverrides(
                projectDir: projectDir,
                pathsByDependency: <String, String>{'a': '../a'},
              )
              .isUnchanged,
          isTrue,
        );
      });

      test('throws for a file whose root is not a map', () {
        overridesFile.writeAsStringSync('- a\n- b\n');

        expect(
          () => io.addPathOverrides(
            projectDir: projectDir,
            pathsByDependency: <String, String>{'a': '../a'},
          ),
          throwsA(
            isA<Exception>().having(
              (Object e) => e.toString(),
              'message',
              contains('expected a YAML map'),
            ),
          ),
        );
      });

      test('throws for a file that is not YAML', () {
        overridesFile.writeAsStringSync('a: [1, 2\n');

        expect(
          () => io.addPathOverrides(
            projectDir: projectDir,
            pathsByDependency: <String, String>{'a': '../a'},
          ),
          throwsA(
            isA<Exception>().having(
              (Object e) => e.toString(),
              'message',
              contains('Cannot parse'),
            ),
          ),
        );
      });
    });

    group('addGitOverrides()', () {
      test('is unchanged for an empty request', () {
        expect(
          io
              .addGitOverrides(
                projectDir: projectDir,
                gitUrlsByDependency: <String, String>{},
                ref: 'feature123',
              )
              .isUnchanged,
          isTrue,
        );
      });

      test('creates the file with a git header', () {
        final edit = io.addGitOverrides(
          projectDir: projectDir,
          gitUrlsByDependency: <String, String>{
            'a': 'git@github.com:user/a.git',
          },
          ref: 'feature123',
        );

        expect(edit.content, startsWith('# Generated by gg_localize_refs'));
        expect(edit.content, contains('feature branch'));
        final git = (overridesOf(edit.content!)['a'] as Map)['git'] as Map;
        expect(git['url'], 'git@github.com:user/a.git');
        expect(git['ref'], 'feature123');
      });

      test('is unchanged when the same refs are already declared', () {
        final first = io.addGitOverrides(
          projectDir: projectDir,
          gitUrlsByDependency: <String, String>{
            'a': 'git@github.com:user/a.git',
          },
          ref: 'feature123',
        );
        overridesFile.writeAsStringSync(first.content!);

        expect(
          io
              .addGitOverrides(
                projectDir: projectDir,
                gitUrlsByDependency: <String, String>{
                  'a': 'git@github.com:user/a.git',
                },
                ref: 'feature123',
              )
              .isUnchanged,
          isTrue,
        );
      });

      test('re-points an override to another ref', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    git:\n'
          '      url: git@github.com:user/a.git\n'
          '      ref: old\n',
        );

        final edit = io.addGitOverrides(
          projectDir: projectDir,
          gitUrlsByDependency: <String, String>{
            'a': 'git@github.com:user/a.git',
          },
          ref: 'feature123',
        );

        final git = (overridesOf(edit.content!)['a'] as Map)['git'] as Map;
        expect(git['ref'], 'feature123');
      });

      test('replaces the local path override of the same dependency', () {
        createSibling('a');
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    path: ../a\n',
        );

        final edit = io.addGitOverrides(
          projectDir: projectDir,
          gitUrlsByDependency: <String, String>{
            'a': 'git@github.com:user/a.git',
          },
          ref: 'feature123',
        );

        final override = overridesOf(edit.content!)['a'] as Map;
        expect(override.containsKey('path'), isFalse);
        expect((override['git'] as Map)['ref'], 'feature123');
      });
    });

    group('removeOwnedOverrides()', () {
      test('is unchanged when there is no file', () {
        expect(
          io
              .removeOwnedOverrides(
                projectDir: projectDir,
                dependencyNames: <String>['a'],
              )
              .isUnchanged,
          isTrue,
        );
      });

      test('deletes the file when only our overrides remain', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    path: ../a\n',
        );

        expect(
          io
              .removeOwnedOverrides(
                projectDir: projectDir,
                dependencyNames: <String>['a'],
              )
              .deleteFile,
          isTrue,
        );
      });

      test('deletes a file that only holds an empty section', () {
        overridesFile.writeAsStringSync('dependency_overrides:\n');

        expect(
          io
              .removeOwnedOverrides(
                projectDir: projectDir,
                dependencyNames: <String>['a'],
              )
              .deleteFile,
          isTrue,
        );
      });

      test('deletes an empty file', () {
        overridesFile.writeAsStringSync('');

        expect(
          io
              .removeOwnedOverrides(
                projectDir: projectDir,
                dependencyNames: <String>['a'],
              )
              .deleteFile,
          isTrue,
        );
      });

      test('keeps hand written entries', () {
        createForeignSibling();
        overridesFile.writeAsStringSync(
          '# keep me\n'
          'dependency_overrides:\n'
          '  a:\n'
          '    path: ../a\n'
          '  other:\n'
          '    path: ../other\n',
        );

        final edit = io.removeOwnedOverrides(
          projectDir: projectDir,
          dependencyNames: <String>['a'],
        );

        expect(edit.deleteFile, isFalse);
        expect(edit.content, contains('# keep me'));
        final overrides = overridesOf(edit.content!);
        expect(overrides.containsKey('a'), isFalse);
        expect((overrides['other'] as Map)['path'], '../other');
      });

      test('keeps other top level keys', () {
        overridesFile.writeAsStringSync(
          'something: 1\n'
          'dependency_overrides:\n'
          '  a:\n'
          '    path: ../a\n',
        );

        final edit = io.removeOwnedOverrides(
          projectDir: projectDir,
          dependencyNames: <String>['a'],
        );

        expect(edit.deleteFile, isFalse);
        expect(edit.content, contains('something: 1'));
      });

      test('leaves an override that is not a path alone', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a: ^1.0.0\n',
        );

        final edit = io.removeOwnedOverrides(
          projectDir: projectDir,
          dependencyNames: <String>['a'],
        );

        expect(edit.isUnchanged, isTrue);
      });

      test('is unchanged when the file has no section but other content', () {
        overridesFile.writeAsStringSync('something: 1\n');

        expect(
          io
              .removeOwnedOverrides(
                projectDir: projectDir,
                dependencyNames: <String>['a'],
              )
              .isUnchanged,
          isTrue,
        );
      });

      test('removes an override whose target directory vanished', () {
        // Leaving local mode must not leave behind an entry pub cannot
        // resolve - the repo would be stuck with a failing pub get.
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  gone:\n'
          '    path: ../gone\n',
        );

        expect(
          io
              .removeOwnedOverrides(
                projectDir: projectDir,
                dependencyNames: <String>[],
              )
              .deleteFile,
          isTrue,
        );
      });

      test(
        'removes an override of a sibling that is no longer a dependency',
        () {
          createSibling('gone');
          overridesFile.writeAsStringSync(
            'dependency_overrides:\n'
            '  gone:\n'
            '    path: ../gone\n',
          );

          expect(
            io
                .removeOwnedOverrides(
                  projectDir: projectDir,
                  dependencyNames: <String>[],
                )
                .deleteFile,
            isTrue,
          );
        },
      );

      test('ignores dependencies that are not overridden', () {
        createForeignSibling();
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  other:\n'
          '    path: ../other\n',
        );

        expect(
          io
              .removeOwnedOverrides(
                projectDir: projectDir,
                dependencyNames: <String>['a'],
              )
              .isUnchanged,
          isTrue,
        );
      });
      test('removes the git overrides of a workspace dependency', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    git:\n'
          '      url: git@github.com:user/a.git\n'
          '      ref: feature123\n',
        );

        expect(
          io
              .removeOwnedOverrides(
                projectDir: projectDir,
                dependencyNames: <String>['a'],
              )
              .deleteFile,
          isTrue,
        );
      });

      test('keeps a git override of a package that is no dependency', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  other:\n'
          '    git:\n'
          '      url: git@github.com:user/other.git\n'
          '      ref: feature123\n',
        );

        expect(
          io
              .removeOwnedOverrides(
                projectDir: projectDir,
                dependencyNames: <String>['a'],
              )
              .isUnchanged,
          isTrue,
        );
      });

      test('keeps a hand written git override with more than url and ref', () {
        // A `tag_pattern` or a `version` is nothing this package writes, so
        // the entry is the user's.
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    git:\n'
          '      url: git@github.com:user/a.git\n'
          '      ref: feature123\n'
          '      path: packages/a\n',
        );

        expect(
          io
              .removeOwnedOverrides(
                projectDir: projectDir,
                dependencyNames: <String>['a'],
              )
              .isUnchanged,
          isTrue,
        );
      });

      test('keeps a git override that is no map', () {
        overridesFile.writeAsStringSync(
          'dependency_overrides:\n'
          '  a:\n'
          '    git: git@github.com:user/a.git\n',
        );

        expect(
          io
              .removeOwnedOverrides(
                projectDir: projectDir,
                dependencyNames: <String>['a'],
              )
              .isUnchanged,
          isTrue,
        );
      });
    });
  });
}
